Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,7 +5,6 @@ on:
       - main
   schedule:
     - cron: "30 0 * * *"
-
 jobs:
   build-frontend:
     runs-on: ubuntu-latest
@@ -16,7 +15,7 @@ jobs:
         with:
           submodules: false
 
-      # Step 2: Cache node_modules to improve build time
+      # Step 2: Cache Node Modules
       - name: Cache Node Modules
         uses: actions/cache@v3
         with:
@@ -25,43 +24,52 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node_modules
 
-      # Step 3: Install dependencies with Yarn
+      # Step 3: Install Dependencies with Yarn
       - name: Install Dependencies 📦
         run: yarn install --frozen-lockfile
         working-directory: web/
 
-      # Step 4: Download DB
+      # Step 4: Verify the Existence of download.mjs
+      - name: Verify `download.mjs` Exists
+        run: |
+          if [ ! -f ./scripts/download.mjs ]; then
+            echo "Error: download.mjs not found in web/scripts/"
+            exit 1
+          fi
+        working-directory: web/
+
+      # Step 5: Download DB using download.mjs
       - name: Download DB 📙
         run: |
           npx zx ./scripts/download.mjs
         working-directory: web/
 
-      # Step 5: Build the frontend
+      # Step 6: Build the frontend
       - name: Build Web 🚧
         run: yarn run generate
         working-directory: web/
 
-      # Step 6: Install Playwright Browsers
+      # Step 7: Install Playwright Browsers
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
         working-directory: web/
 
-      # Step 7: Run Playwright Tests
+      # Step 8: Run Playwright Tests
       - name: Run Playwright Tests
         run: yarn playwright test
         working-directory: web/
 
-      # Step 8: Upload Playwright Test Reports
-      - uses: actions/upload-artifact@v3
+      # Step 9: Upload Playwright Test Reports
+      - uses: actions/upload-artifact@v4
         if: always()
         with:
           name: playwright-report
           path: web/playwright-report/
           retention-days: 30
 
-      # Step 9: Deploy to GitHub Pages
+      # Step 10: Deploy to GitHub Pages
       - name: Deploy 🚀
-        uses: JamesIves/github-pages-deploy-action@v4
+        uses: JamesIves/github-pages-deploy-action@v4.2.3
         with:
           branch: gh-pages
           folder: web/dist/static/
